name: SurvivalMcraft
main: xyz.thesteve.survivalmcraft.Main
version: 1.0.1
api-version: 1.16
author: TheSteveXYZ
website: https://thesteve.xyz

commands:
  spawn:
    description: Teleports you to the spawn.
    usage: /<command>
    aliases: sp
  home:
    description: Teleports you to your home
    usage: /<command>
    aliases: h
  sethome:
    description: Sets your home
    usage: /<command>
    aliases: seth
  ping:
    description: Gets your or other player's ping
    usage: /<command> [<Player>]
    aliases: p